### ISSUE TITLE
Error with URL encoded CMIS query

### ISSUE THREAD

**Issue by llouw** [vneecious/sap-cap-sdm-plugin#19]
I tried the `entity Files` example you have in the Readme and it failed.

When the query for `cmis:document` is built it gets encoded incorrectly.

The request to CMIS looks like `q=SELECT%2520*%2520FROM%2520cmis%253Adocument` instead of `SELECT%20cmis%3AobjectId%2C%20cmis%3Aname%20FROM%20cmis%3Adocument`.

Note that `%2520` does not work but `%20` does.

**Comment by llouw** [comment]
I found that if I change  `q: encodeURIComponent(statement),` to `q: statement,` that the query executes fine

**Comment by vneecious** [comment]
Hi @llouw-drs. I just tried both of these test scenarios, and they worked fine. I think I didn't get what the issue here is. Can you give me a sample? 


```
  test('query list of objects', async () => {
    const response = await GET(
      `/crud/Files?$filter=name eq '${file.name}'&$count=true`,
    );
    expect(response.status).toBe(200);
    expect(response.data?.['@odata.count']).toBe(1);
  });

  test('query list of objects limiting the number of fields', async () => {
    const response = await GET(`/crud/Files?$select=id,name`);
    expect(response.status).toBe(200);
    expect(response.data.value[0].id).toBeTruthy();
    expect(response.data.value[0].name).toBeTruthy();
  });
```

Thanks!

**Comment by llouw** [comment]
Hi @vneecious,

Here the error for `/Files?$filter=name eq '${file.name}'&$count=true`. 

Note the encoding of the URL parameter. It looks like as if it is geting encoded twice. I'm running CAP v7.

```- AxiosError: Request failed with status code 400
    at settle (/infield/node_modules/axios/dist/node/axios.cjs:1967:12)
    at Unzip.handleStreamEnd (/infield/node_modules/axios/dist/node/axios.cjs:3066:11)
    at Unzip.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Axios.request (/infield/node_modules/axios/dist/node/axios.cjs:3877:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async OpenApiRequestBuilder.execute (/infield/node_modules/@sap-cloud-sdk/openapi/dist/openapi-request-builder.js:88:26)
    at async ApplicationService.onRead (/infield/node_modules/sap-cap-sdm-plugin/lib/handlers/index.js:75:33)
    at async next (/infield/node_modules/@sap/cds/lib/srv/srv-dispatch.js:79:17)
    at async ApplicationService.handle (/infield/node_modules/@sap/cds/lib/srv/srv-dispatch.js:77:10)
    at async _readCollection (/infield/node_modules/@sap/cds/libx/_runtime/cds-services/adapter/odata-v4/handlers/read.js:251:19)
    at async /infield/node_modules/@sap/cds/libx/_runtime/cds-services/adapter/odata-v4/handlers/read.js:546:16 {
  code: 'ERR_BAD_REQUEST',```

```
    method: 'get',
    baseURL: 'https://api-sdm-di.cfapps.ap10.hana.ondemand.com',
    params: {
      cmisSelector: 'query',
      q: 'SELECT%2520*%2520FROM%2520cmis%253Adocument',
      _charset: 'UTF-8',
      succinct: 'true'
    },
    proxy: false,
    url: '/browser/096dec72-9d77-4054-bfcc-d40fc8912644',
    middleware: [],
    data: undefined
```

**Comment by vneecious** [comment]
Hum... I'm guessing you are running this query from a browser or a client that automatically encodes the URI params, am I righ? It would explain why all my test cases work fine (they're always being sent unencoded).

**Comment by vneecious** [comment]
Ok, so basically [what I did](https://github.com/vneecious/sap-cap-sdm-plugin/commit/bca299be9d934977facc6388645283d5487ff216) was ensure that we call encodeURIComponent on queries after we've decoded them first. This way, we avoid accidentally encoding them twice, keeping everything smooth and accurate.

Thank you very much for this finding. I really appreciate it 😄
